import { format } from "date-fns";

export const downloadMessagesCSV = (requests: any[]) => {
  const headers = ["Date", "Table", "Type", "Message", "Customer Name", "Phone", "Status"];
  const rows = requests.map((r) => [
    format(new Date(r.created_at), "yyyy-MM-dd HH:mm"),
    r.table_number || "—",
    r.type,
    r.message || "",
    r.name || "",
    r.phone || "",
    r.resolved ? "Resolved" : "Pending",
  ]);

  const csvContent = [headers, ...rows]
    .map((e) => e.map((val) => `"${String(val).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `feedback_report_${format(new Date(), "yyyy-MM-dd")}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const downloadMessagesPDF = (requests: any[], restaurantName: string) => {
  // Simple print approach for PDF
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = `
    <html>
      <head>
        <title>Feedback Report - ${restaurantName}</title>
        <style>
          body { font-family: sans-serif; padding: 20px; }
          h1 { color: #333; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
          th { background-color: #f2f2f2; }
          .footer { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Feedback & Requests Report</h1>
        <p><strong>Pharmacy:</strong> ${restaurantName}</p>
        <p><strong>Date Generated:</strong> ${format(new Date(), "PPpp")}</p>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Table</th>
              <th>Type</th>
              <th>Message</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${requests.map(r => `
              <tr>
                <td>${format(new Date(r.created_at), "MMM d, HH:mm")}</td>
                <td>Table ${r.table_number || "—"}</td>
                <td style="text-transform: capitalize;">${r.type}</td>
                <td>${r.message || "—"}</td>
                <td>${r.resolved ? "Resolved" : "Pending"}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>
        <div class="footer">Generated by PharmIQ</div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.print();
};
