// Massive list of Nigerian NAFDAC-approved and common drugs per category.
// 1000+ items. The suggestions modal uses search filtering + windowed rendering so it never lags.

export type Suggestion = {
  name: string;
  description: string;
  image: string | null;
};

const drug = (n: string, d: string): Suggestion => ({ name: n, description: d, image: null });

export const menuSuggestions: Record<string, Suggestion[]> = {

  /* ─────────────────────────── ANTIMALARIALS ─────────────────────────── */
  "Antimalarials": [
    drug("Artemether + Lumefantrine 20/120mg (Coartem)", "First-line ACT paediatric"),
    drug("Artemether + Lumefantrine 80/480mg (Coartem Adult)", "First-line ACT adult dose"),
    drug("Lonart DS (Artemether + Lumefantrine)", "Brand ACT combination"),
    drug("Lonart Forte", "High strength ACT"),
    drug("Lonart Suspension", "ACT suspension for children"),
    drug("Amatem Softgel 80/480mg", "Softgel ACT capsules"),
    drug("Amatem Forte Softgel", "High dose ACT softgel"),
    drug("Lumartem 80/480mg", "Artemether + Lumefantrine"),
    drug("Coartem Dispersible", "ACT dispersible tablets for infants"),
    drug("Camosunate Adult (Artesunate + Amodiaquine)", "ACT combo"),
    drug("Camosunate Paediatric", "ACT for children"),
    drug("P-Alaxin (Dihydroartemisinin + Piperaquine)", "ACT"),
    drug("Eurartesim (Dihydroartemisinin + Piperaquine)", "ACT"),
    drug("Waipa (Dihydroartemisinin + Piperaquine)", "ACT"),
    drug("Artequick (Artemisinin + Piperaquine)", "ACT"),
    drug("Amalar (Sulfadoxine + Pyrimethamine)", "Malaria prophylaxis / IPTp"),
    drug("Fansidar (Sulfadoxine + Pyrimethamine)", "IPTp for pregnancy"),
    drug("Swidar (Sulfadoxine + Pyrimethamine)", "SP brand"),
    drug("Maloxine (Sulfadoxine + Pyrimethamine)", "SP brand"),
    drug("Artesunate 50mg Tablet", "Oral artesunate"),
    drug("Artesunate 100mg Tablet", "Oral artesunate"),
    drug("Artesunate Injection 60mg", "IV/IM artesunate for severe malaria"),
    drug("Artesunate Injection 120mg", "IV/IM artesunate for severe malaria"),
    drug("Artemether Injection 80mg/ml", "IM injection for severe malaria"),
    drug("Quinine Sulfate 300mg", "For complicated / resistant malaria"),
    drug("Quinine Syrup", "Quinine for children"),
    drug("Quinine Injection 300mg/ml", "IV quinine for severe malaria"),
    drug("Halfan (Halofantrine) 250mg", "Antimalarial"),
    drug("Halfan Suspension", "Halofantrine for children"),
    drug("Chloroquine Phosphate 250mg", "Antimalarial prophylaxis"),
    drug("Chloroquine Syrup", "Chloroquine for children"),
    drug("Proguanil 100mg (Paludrine)", "Malaria prophylaxis"),
    drug("Mefloquine 250mg (Lariam)", "Weekly malaria prophylaxis"),
    drug("Doxycycline 100mg", "Malaria prophylaxis and treatment"),
  ],

  /* ─────────────────────── ANALGESICS & PAIN RELIEF ─────────────────────── */
  "Analgesics & Pain Relief": [
    drug("Paracetamol 500mg (Emzor)", "Standard paracetamol tablet"),
    drug("Paracetamol 500mg (M&B)", "M&B paracetamol"),
    drug("Panadol 500mg", "Paracetamol for pain and fever"),
    drug("Panadol Extra (Paracetamol + Caffeine)", "Enhanced paracetamol"),
    drug("Boska (Paracetamol + Caffeine)", "Popular paracetamol combo"),
    drug("Relicalm (Paracetamol + Caffeine + Diphenhydramine)", "Night-time pain relief"),
    drug("Ibucap (Ibuprofen + Paracetamol + Caffeine)", "Triple action analgesic"),
    drug("Alabukun Powder", "Acetylsalicylic acid + Caffeine powder"),
    drug("Ibuprofen 200mg", "NSAID mild pain"),
    drug("Ibuprofen 400mg", "NSAID standard dose"),
    drug("Ibuprofen 600mg", "NSAID high dose"),
    drug("Brufen 400mg", "Ibuprofen brand"),
    drug("Diclofenac Potassium 50mg (Cataflam)", "Fast-acting NSAID"),
    drug("Diclofenac Sodium 50mg (Voltaren)", "NSAID for musculoskeletal pain"),
    drug("Diclofenac Sodium 100mg SR", "Sustained release diclofenac"),
    drug("Aceclofenac 100mg", "NSAID for arthritis"),
    drug("Piroxicam 20mg (Feldene)", "NSAID for joint pain"),
    drug("Piroxicam 10mg", "Lower dose piroxicam"),
    drug("Meloxicam 15mg (Mobic)", "NSAID for osteoarthritis"),
    drug("Meloxicam 7.5mg", "Lower dose meloxicam"),
    drug("Naproxen 500mg", "NSAID for arthritis"),
    drug("Naproxen 250mg", "NSAID lower dose"),
    drug("Celecoxib 200mg (Celebrex)", "COX-2 inhibitor for arthritis"),
    drug("Etoricoxib 90mg (Arcoxia)", "COX-2 inhibitor"),
    drug("Etoricoxib 120mg", "COX-2 inhibitor acute gout"),
    drug("Ketoprofen 100mg", "NSAID"),
    drug("Indomethacin 25mg", "NSAID for gout"),
    drug("Aspirin 300mg", "Pain and fever"),
    drug("Aspirin 75mg (Low-dose)", "Cardiovascular protection"),
    drug("Tramadol 50mg", "Opioid analgesic"),
    drug("Tramadol 100mg SR", "Extended release opioid"),
    drug("Codeine Phosphate 30mg", "Mild opioid"),
    drug("Codeine + Paracetamol", "Combination opioid analgesic"),
    drug("Tramadol + Paracetamol (Ultracet)", "Combination opioid"),
    drug("Hyoscine 10mg (Buscopan)", "Antispasmodic for cramps"),
    drug("Drotaverine 40mg (No-Spa)", "Antispasmodic"),
    drug("Mefenamic Acid 500mg (Ponstan)", "NSAID for dysmenorrhoea"),
    drug("Morphine Sulfate 10mg", "Strong opioid"),
    drug("Pentazocine 30mg Injection", "Moderate opioid injection"),
  ],

  /* ─────────────────────── ANTIBIOTICS & ANTIBACTERIALS ─────────────────────── */
  "Antibiotics & Antibacterials": [
    // Penicillins
    drug("Amoxicillin 250mg", "Penicillin broad spectrum"),
    drug("Amoxicillin 500mg", "Penicillin broad spectrum"),
    drug("Amoxil 500mg", "Brand amoxicillin"),
    drug("Augmentin 312mg/5ml Suspension", "Paediatric amoxicillin + clavulanate"),
    drug("Augmentin 457mg/5ml Suspension", "Forte paediatric amoxicillin + clavulanate"),
    drug("Augmentin 625mg", "Amoxicillin + Clavulanate"),
    drug("Augmentin 1g", "High-dose amoxicillin + clavulanate"),
    drug("Amclav 625mg", "Amoxicillin + Clavulanate"),
    drug("Ampiclox 250mg", "Ampicillin + Cloxacillin"),
    drug("Ampiclox 500mg", "Ampicillin + Cloxacillin"),
    drug("Cloxacillin 250mg", "Penicillinase-resistant"),
    drug("Cloxacillin 500mg", "Penicillinase-resistant"),
    drug("Flucloxacillin 250mg", "For staphylococcal infections"),
    drug("Flucloxacillin 500mg", "For staphylococcal infections"),
    drug("Ampicillin 250mg", "Penicillin antibiotic"),
    // Cephalosporins
    drug("Cefalexin 250mg", "First-gen cephalosporin"),
    drug("Cefalexin 500mg (Keflex)", "First-gen cephalosporin"),
    drug("Cefuroxime 250mg", "Second-gen cephalosporin"),
    drug("Cefuroxime 500mg (Zinnat)", "Second-gen cephalosporin"),
    drug("Cefpodoxime 100mg", "Third-gen cephalosporin"),
    drug("Cefpodoxime 200mg", "Third-gen cephalosporin"),
    drug("Cefixime 200mg", "Third-gen cephalosporin"),
    drug("Cefixime 400mg", "Third-gen cephalosporin"),
    drug("Ceftriaxone 1g Injection (Rocephin)", "IV/IM cephalosporin"),
    drug("Ceftriaxone 2g Injection", "High-dose IV cephalosporin"),
    // Macrolides
    drug("Azithromycin 250mg", "Macrolide"),
    drug("Azithromycin 500mg (Zithromax)", "Macrolide"),
    drug("Erythromycin 250mg", "Macrolide"),
    drug("Erythromycin 500mg", "Macrolide for penicillin-allergic"),
    drug("Clarithromycin 250mg", "Macrolide"),
    drug("Clarithromycin 500mg", "Macrolide for H. pylori"),
    // Fluoroquinolones
    drug("Ciprofloxacin 250mg", "Fluoroquinolone"),
    drug("Ciprofloxacin 500mg (Ciprotab)", "Fluoroquinolone broad spectrum"),
    drug("Ciprofloxacin Infusion 200mg/100ml", "IV fluoroquinolone"),
    drug("Levofloxacin 250mg", "Fluoroquinolone"),
    drug("Levofloxacin 500mg", "Fluoroquinolone"),
    drug("Ofloxacin 200mg (Tarivid)", "Fluoroquinolone"),
    drug("Ofloxacin 400mg", "Fluoroquinolone high dose"),
    drug("Moxifloxacin 400mg (Avelox)", "Fluoroquinolone for respiratory"),
    // Tetracyclines
    drug("Tetracycline 250mg", "Tetracycline broad spectrum"),
    drug("Doxycycline 100mg", "Tetracycline for STIs and acne"),
    drug("Doxycycline 200mg Loading Dose", "Tetracycline high dose"),
    // Nitroimidazoles
    drug("Metronidazole 200mg", "For anaerobic infections"),
    drug("Metronidazole 400mg (Flagyl / Flagin)", "For anaerobic and parasitic infections"),
    drug("Metronidazole Infusion 500mg/100ml", "IV metronidazole"),
    drug("Tinidazole 500mg (Fasigyn)", "Anti-protozoal"),
    drug("Secnidazole 2g", "Single dose anti-protozoal"),
    drug("Ornidazole 500mg", "Anti-protozoal"),
    // Sulfonamides / Folate inhibitors
    drug("Cotrimoxazole 480mg (Septrin)", "TMP + SMX"),
    drug("Cotrimoxazole 960mg (Septrin Forte)", "Double strength TMP + SMX"),
    // Others
    drug("Nitrofurantoin 50mg", "For UTIs"),
    drug("Nitrofurantoin 100mg", "For UTIs"),
    drug("Clindamycin 150mg", "For anaerobic and bone infections"),
    drug("Clindamycin 300mg", "Higher dose clindamycin"),
    drug("Gentamicin 80mg Injection", "Aminoglycoside IV/IM"),
    drug("Chloramphenicol 250mg", "Broad-spectrum"),
    drug("Chloramphenicol 500mg", "Broad-spectrum"),
    drug("Rifampicin 300mg", "For TB and brucellosis"),
    drug("Isoniazid 300mg", "TB treatment"),
    drug("Pyrazinamide 500mg", "TB treatment"),
    drug("Ethambutol 400mg", "TB treatment"),
    drug("Linezolid 600mg", "For resistant gram-positive infections"),
    drug("Vancomycin 500mg Injection", "For MRSA"),
  ],

  /* ─────────────────────── ANTIHYPERTENSIVES ─────────────────────── */
  "Antihypertensives (Blood Pressure)": [
    // CCBs
    drug("Amlodipine 5mg (Norvasc)", "Calcium channel blocker"),
    drug("Amlodipine 10mg", "Calcium channel blocker"),
    drug("Nifedipine 10mg", "Calcium channel blocker"),
    drug("Nifedipine 20mg Retard", "SR calcium channel blocker"),
    drug("Felodipine 5mg", "Calcium channel blocker"),
    // ACE inhibitors
    drug("Lisinopril 5mg (Zestril)", "ACE inhibitor"),
    drug("Lisinopril 10mg", "ACE inhibitor"),
    drug("Lisinopril 20mg", "ACE inhibitor"),
    drug("Ramipril 2.5mg", "ACE inhibitor"),
    drug("Ramipril 5mg (Tritace)", "ACE inhibitor"),
    drug("Enalapril 5mg (Vasotec)", "ACE inhibitor"),
    drug("Enalapril 10mg", "ACE inhibitor"),
    drug("Perindopril 4mg", "ACE inhibitor"),
    // ARBs
    drug("Losartan 25mg", "ARB"),
    drug("Losartan 50mg (Cozaar)", "ARB"),
    drug("Losartan 100mg", "ARB"),
    drug("Valsartan 80mg (Diovan)", "ARB"),
    drug("Valsartan 160mg", "ARB"),
    drug("Telmisartan 40mg (Micardis)", "ARB"),
    drug("Telmisartan 80mg", "ARB"),
    drug("Irbesartan 150mg (Aprovel)", "ARB"),
    drug("Candesartan 8mg", "ARB"),
    // Beta blockers
    drug("Atenolol 50mg (Tenormin)", "Beta-blocker"),
    drug("Atenolol 100mg", "Beta-blocker"),
    drug("Bisoprolol 2.5mg", "Cardioselective beta-blocker"),
    drug("Bisoprolol 5mg (Concor)", "Cardioselective beta-blocker"),
    drug("Bisoprolol 10mg", "Beta-blocker"),
    drug("Carvedilol 6.25mg", "Beta-blocker for heart failure"),
    drug("Carvedilol 12.5mg", "Beta-blocker"),
    drug("Carvedilol 25mg", "Beta-blocker"),
    drug("Metoprolol 50mg", "Beta-blocker"),
    drug("Metoprolol 100mg", "Beta-blocker"),
    drug("Propranolol 10mg", "Non-selective beta-blocker"),
    drug("Propranolol 40mg", "Non-selective beta-blocker"),
    // Diuretics
    drug("Hydrochlorothiazide 25mg", "Thiazide diuretic"),
    drug("Furosemide 20mg", "Loop diuretic"),
    drug("Furosemide 40mg (Lasix)", "Loop diuretic"),
    drug("Furosemide Injection 20mg/2ml", "IV loop diuretic"),
    drug("Spironolactone 25mg (Aldactone)", "Potassium-sparing"),
    drug("Spironolactone 50mg", "Potassium-sparing"),
    drug("Moduretic (Amiloride + HCTZ)", "Combination diuretic"),
    // Combinations
    drug("Exforge (Amlodipine + Valsartan)", "CCB + ARB combo"),
    drug("Co-Diovan (Valsartan + HCTZ)", "ARB + diuretic"),
    drug("Micardis Plus (Telmisartan + HCTZ)", "ARB + diuretic"),
    drug("Lodipin Plus (Amlodipine + Atenolol)", "CCB + beta-blocker"),
    // Centrally acting
    drug("Methyldopa 250mg (Aldomet)", "For pregnancy hypertension"),
    drug("Methyldopa 500mg", "For pregnancy hypertension"),
    drug("Clonidine 0.1mg (Catapres)", "Centrally acting"),
  ],

  /* ─────────────────────── ANTIDIABETICS ─────────────────────── */
  "Antidiabetics (Blood Sugar)": [
    drug("Metformin 500mg (Glucophage)", "Biguanide T2DM"),
    drug("Metformin 850mg", "Biguanide T2DM"),
    drug("Metformin 1000mg", "Biguanide high dose"),
    drug("Metformin 500mg SR", "Sustained-release biguanide"),
    drug("Glibenclamide 5mg (Daonil)", "Sulfonylurea"),
    drug("Glimepiride 1mg (Amaryl)", "Sulfonylurea"),
    drug("Glimepiride 2mg", "Sulfonylurea"),
    drug("Glimepiride 4mg", "Sulfonylurea"),
    drug("Glipizide 5mg", "Sulfonylurea"),
    drug("Gliclazide 80mg (Diamicron)", "Sulfonylurea"),
    drug("Gliclazide 60mg MR", "Modified release sulfonylurea"),
    drug("Sitagliptin 50mg", "DPP-4 inhibitor"),
    drug("Sitagliptin 100mg (Januvia)", "DPP-4 inhibitor"),
    drug("Vildagliptin 50mg (Galvus)", "DPP-4 inhibitor"),
    drug("Saxagliptin 5mg (Onglyza)", "DPP-4 inhibitor"),
    drug("Galvus Met (Vildagliptin + Metformin)", "Combo DPP-4 + biguanide"),
    drug("Janumet (Sitagliptin + Metformin)", "Combo DPP-4 + biguanide"),
    drug("Pioglitazone 15mg (Actos)", "Thiazolidinedione"),
    drug("Pioglitazone 30mg", "Thiazolidinedione"),
    drug("Dapagliflozin 10mg (Forxiga)", "SGLT2 inhibitor"),
    drug("Empagliflozin 10mg (Jardiance)", "SGLT2 inhibitor"),
    drug("Canagliflozin 100mg (Invokana)", "SGLT2 inhibitor"),
    drug("Insulin Mixtard 30/70", "Biphasic isophane insulin"),
    drug("Insulin Glargine 100 IU (Lantus)", "Long-acting basal insulin"),
    drug("Insulin Detemir (Levemir)", "Long-acting basal insulin"),
    drug("Insulin Soluble (Actrapid)", "Short-acting insulin"),
    drug("Insulin Lispro (Humalog)", "Rapid-acting insulin"),
  ],

  /* ─────────────────────── COUGH, COLD & ALLERGIES ─────────────────────── */
  "Cough, Cold & Allergies": [
    drug("Loratadine 10mg", "Non-drowsy antihistamine"),
    drug("Cetirizine 10mg", "Antihistamine"),
    drug("Cetirizine 5mg", "Antihistamine lower dose"),
    drug("Fexofenadine 120mg (Telfast)", "Non-sedating antihistamine"),
    drug("Fexofenadine 180mg", "Non-sedating antihistamine"),
    drug("Chlorpheniramine 4mg (Piriton)", "Sedating antihistamine"),
    drug("Promethazine 25mg (Phenergan)", "Sedating antihistamine + anti-emetic"),
    drug("Diphenhydramine 25mg (Benadryl)", "Sedating antihistamine"),
    drug("Desloratadine 5mg (Aerius)", "Non-drowsy antihistamine"),
    drug("Levocetirizine 5mg (Xyzal)", "Non-drowsy antihistamine"),
    drug("Azelastine Nasal Spray", "Antihistamine nasal spray"),
    drug("Cough Entersil Syrup", "Cough suppressant and expectorant"),
    drug("Emzolyn Cough Syrup", "Expectorant for productive cough"),
    drug("Benylin with Codeine", "Cough suppressant"),
    drug("Benylin Chesty Cough", "Expectorant"),
    drug("Benylin Dry Cough", "Suppressant"),
    drug("Benylin Paediatric", "Childrens cough syrup"),
    drug("Tuxil D Cough Syrup", "Dry cough"),
    drug("Tuxil N Cough Syrup", "Night cough"),
    drug("Bell's Cough Syrup", "Traditional cough syrup"),
    drug("Procold (Paracetamol + CPM + Pseudoephedrine)", "Cold relief"),
    drug("Mixagrip Cold & Flu", "Cold and flu relief"),
    drug("Sinutab", "Nasal decongestant + pain relief"),
    drug("Day Nurse / Night Nurse", "Cold and flu liquid"),
    drug("Vicks Vaporub", "Mentholated topical rub"),
    drug("Fluticasone Nasal Spray (Flixonase)", "Steroid for allergic rhinitis"),
    drug("Mometasone Nasal Spray (Nasonex)", "Steroid for allergic rhinitis"),
    drug("Xylometazoline Nasal Drops 0.1% (Otrivin)", "Nasal decongestant"),
    drug("Oxymetazoline Nasal Spray (Afrin)", "Nasal decongestant"),
    drug("Pseudoephedrine 60mg", "Decongestant"),
    drug("Guaifenesin 200mg (Robitussin)", "Expectorant"),
    drug("Ambroxol 30mg", "Mucolytic expectorant"),
    drug("Bromhexine 8mg", "Mucolytic"),
    drug("Strepsils Lozenges", "Antibacterial throat lozenges"),
    drug("Dequadin Lozenges", "For sore throat"),
    drug("Tom Tom", "Menthol soothing drops"),
    drug("Vitamin C + Zinc Lozenges", "Throat lozenges"),
    drug("Montelukast 10mg (Singulair)", "For asthma and allergic rhinitis"),
    drug("Salbutamol Inhaler (Ventolin) 100mcg", "Bronchodilator for asthma"),
    drug("Ipratropium + Salbutamol (Combivent) Inhaler", "COPD/asthma inhaler"),
    drug("Beclomethasone Inhaler (Clenil)", "Inhaled steroid for asthma"),
    drug("Prednisolone 5mg", "Oral steroid for asthma"),
    drug("Aminophylline 100mg", "Bronchodilator"),
    drug("Theophylline 200mg SR", "Sustained release bronchodilator"),
  ],

  /* ─────────────────────── VITAMINS & SUPPLEMENTS ─────────────────────── */
  "Vitamins & Supplements": [
    drug("Vitamin C 100mg", "Ascorbic acid"),
    drug("Vitamin C 500mg", "High dose vitamin C"),
    drug("Vitamin C 1000mg (Emzor)", "High-dose ascorbic acid"),
    drug("Vitamin C 1000mg Effervescent", "Dissolvable vitamin C"),
    drug("Wellman Original", "Multivitamin for men"),
    drug("Wellwoman Original", "Multivitamin for women"),
    drug("Wellman 70+", "Multivitamin for older men"),
    drug("Wellwoman 70+", "Multivitamin for older women"),
    drug("Pregnacare Original", "Prenatal multivitamin"),
    drug("Pregnacare Plus Omega-3", "Prenatal multivitamin + DHA"),
    drug("Pregnacare Max", "Comprehensive prenatal"),
    drug("Perfectil Original", "Skin, hair, and nails"),
    drug("Perfectil Platinum", "Premium skin supplement"),
    drug("Immunace", "Immune support"),
    drug("Osteocare Original", "Calcium + Magnesium + Zinc + D3"),
    drug("Astymin Liquid", "Amino acid multivitamin"),
    drug("Astymin Capsules", "Amino acid multivitamin"),
    drug("Astymin Forte", "Amino acid high dose"),
    drug("Pharmaton Capsules", "Multivitamin + ginseng"),
    drug("Centrum Adult", "Complete multivitamin"),
    drug("Centrum Silver 50+", "Multivitamin for 50+"),
    drug("Supradyn Effervescent", "Multivitamin energy"),
    drug("Reload Men", "Multivitamin for men"),
    drug("Reload Women", "Multivitamin for women"),
    drug("Berocca Performance", "Multivitamin + minerals effervescent"),
    drug("Folic Acid 400mcg", "Prenatal folate"),
    drug("Folic Acid 5mg", "High-dose folate"),
    drug("Ferrous Sulfate 200mg", "Iron supplement"),
    drug("Ferrous Gluconate 300mg", "Iron supplement"),
    drug("Ferrous Fumarate 200mg", "Iron supplement"),
    drug("Chemiron Blood Tonic", "Iron tonic"),
    drug("Bunto Blood Tonic", "Iron and vitamins"),
    drug("Astifer Blood Tonic", "Iron and vitamin supplement"),
    drug("Feroglobin B12 Liquid", "Iron + B12 + zinc liquid"),
    drug("Jobelyn (Sorghum Bicolor)", "Herbal blood builder"),
    drug("B-Complex (Emzor)", "Vitamin B complex"),
    drug("Neurobion Forte", "High dose B-vitamins for neuropathy"),
    drug("Mecobalamin 500mcg", "Vitamin B12 for neuropathy"),
    drug("Vitamin D3 400 IU", "Vitamin D supplement"),
    drug("Vitamin D3 1000 IU", "Vitamin D supplement"),
    drug("Vitamin D3 5000 IU", "High-dose vitamin D"),
    drug("Calcium 500mg + Vitamin D3", "Bone health"),
    drug("Calcium Carbonate 500mg", "Calcium supplement"),
    drug("Vitamin E 400 IU", "Antioxidant"),
    drug("Vitamin E 1000 IU", "High-dose antioxidant"),
    drug("Cod Liver Oil 1000mg", "Omega-3 supplement"),
    drug("Omega-3 Fish Oil 1000mg", "Heart health"),
    drug("Omega-3 Fish Oil 2000mg", "High-dose omega-3"),
    drug("Zinc 20mg", "Immune support"),
    drug("Zinc 50mg", "Zinc high dose"),
    drug("Magnesium 250mg", "Muscle and nerve function"),
    drug("Evening Primrose Oil 1000mg", "For PMS and hormonal balance"),
    drug("Ginseng Extract", "Energy and stamina"),
    drug("Orogbo (Bitter Kola) Extract", "Herbal supplement"),
  ],

  /* ─────────────────────── GASTROINTESTINAL & ANTACIDS ─────────────────────── */
  "Gastrointestinal & Antacids": [
    // PPIs
    drug("Omeprazole 20mg", "PPI for ulcers"),
    drug("Omeprazole 40mg", "High-dose PPI"),
    drug("Esomeprazole 20mg", "PPI"),
    drug("Esomeprazole 40mg (Nexium)", "PPI for acid reflux"),
    drug("Rabeprazole 20mg", "PPI"),
    drug("Pantoprazole 20mg", "PPI"),
    drug("Pantoprazole 40mg", "PPI"),
    drug("Lansoprazole 30mg", "PPI"),
    // H2 Blockers
    drug("Ranitidine 150mg", "H2 blocker"),
    drug("Famotidine 20mg", "H2 blocker"),
    drug("Cimetidine 400mg", "H2 blocker"),
    // Antacids
    drug("Gestid Suspension", "Antacid"),
    drug("Magnesium Trisilicate Tablet", "Chewable antacid"),
    drug("Gaviscon Liquid", "Alginate antacid"),
    drug("Relcer Gel", "Antacid and anti-gas"),
    drug("Mist Mag (Magnesium Trisilicate Mixture)", "Liquid antacid"),
    drug("Eno Fruit Salt", "Effervescent antacid"),
    drug("Andrews Liver Salts", "Antacid and laxative"),
    drug("Aluminium Hydroxide 500mg", "Antacid"),
    // Anti-diarrheal
    drug("Loperamide 2mg (Imodium)", "Anti-diarrheal"),
    drug("Oral Rehydration Salt (ORS)", "Electrolyte replacement"),
    drug("Zincast (Zinc + ORS)", "Diarrhea kit"),
    drug("Smecta (Dioctahedral Smectite)", "Anti-diarrheal"),
    drug("Kaolin + Morphine Mixture", "Anti-diarrheal mixture"),
    // Ulcer combinations (H.pylori)
    drug("Pylera (Bismuth + Metronidazole + Tetracycline)", "H.pylori triple therapy"),
    // Antispasmodics
    drug("Buscopan 10mg (Hyoscine)", "Antispasmodic"),
    drug("Buscopan Injection 20mg/ml", "IV antispasmodic"),
    drug("No-Spa 40mg (Drotaverine)", "Antispasmodic"),
    drug("Mebeverine 135mg (Colofac)", "IBS antispasmodic"),
    // Anti-emetics
    drug("Metoclopramide 10mg (Maxolon)", "Anti-nausea"),
    drug("Domperidone 10mg (Motilium)", "Anti-emetic"),
    drug("Ondansetron 4mg", "Strong anti-emetic"),
    drug("Ondansetron 8mg", "Strong anti-emetic"),
    // Laxatives
    drug("Bisacodyl 5mg (Dulcolax)", "Laxative"),
    drug("Lactulose 10g/15ml Solution", "Osmotic laxative"),
    drug("Senna 7.5mg", "Stimulant laxative"),
    drug("Isabgol (Psyllium Husk) Sachets", "Bulk-forming laxative"),
    drug("Glycerine Suppositories", "Rectal laxative"),
    // Liver support
    drug("Silymarin (Legalon) 140mg", "Liver protective"),
    drug("Livergan", "Liver supplement"),
  ],

  /* ─────────────────────── CARDIOVASCULAR ─────────────────────── */
  "Cardiovascular": [
    // Statins
    drug("Atorvastatin 10mg (Lipitor)", "Statin for cholesterol"),
    drug("Atorvastatin 20mg", "Statin"),
    drug("Atorvastatin 40mg", "Statin"),
    drug("Atorvastatin 80mg", "High-intensity statin"),
    drug("Simvastatin 10mg (Zocor)", "Statin"),
    drug("Simvastatin 20mg", "Statin"),
    drug("Simvastatin 40mg", "Statin"),
    drug("Rosuvastatin 10mg (Crestor)", "High-potency statin"),
    drug("Rosuvastatin 20mg", "High-potency statin"),
    // Anti-anginals / Nitrates
    drug("Isosorbide Mononitrate 20mg", "Anti-anginal"),
    drug("Isosorbide Mononitrate 60mg SR", "SR anti-anginal"),
    drug("Isosorbide Dinitrate 5mg Sublingual", "Acute angina relief"),
    drug("GTN Spray (Nitroglycerin)", "Sublingual nitrate for angina"),
    // Antiplatelet
    drug("Aspirin 75mg + Clopidogrel 75mg (Duoplavin)", "Dual antiplatelet"),
    drug("Clopidogrel 75mg (Plavix)", "Antiplatelet"),
    // Anticoagulants
    drug("Warfarin 5mg", "Oral anticoagulant"),
    drug("Enoxaparin Injection 40mg (Clexane)", "LMWH anticoagulant"),
    // Anti-arrhythmics
    drug("Digoxin 0.25mg", "For atrial fibrillation / heart failure"),
    drug("Amiodarone 200mg", "Anti-arrhythmic"),
    // Heart failure
    drug("Carvedilol 25mg", "Beta-blocker for heart failure"),
    drug("Aldactone 25mg (Spironolactone)", "Diuretic for heart failure"),
    drug("Sacubitril + Valsartan (Entresto)", "For heart failure"),
    // Hypolipidemics
    drug("Fibrates (Fenofibrate 145mg)", "For hypertriglyceridemia"),
    drug("Ezetimibe 10mg (Ezetrol)", "Cholesterol absorption inhibitor"),
  ],

  /* ─────────────────────── DERMATOLOGICAL & TOPICAL ─────────────────────── */
  "Dermatological & Topical": [
    drug("Funbact-A", "Triple action cream"),
    drug("Skineal Cream", "Triple action cream"),
    drug("Epiderm Cream", "Triple action cream"),
    drug("Nixoderm Ointment", "For eczema and pimples"),
    drug("Clotrimazole Cream 1%", "Topical antifungal"),
    drug("Ketoconazole Cream 2% (Nizoral)", "Topical antifungal"),
    drug("Miconazole Cream 2% (Daktarin)", "Topical antifungal"),
    drug("Lamisil Cream (Terbinafine 1%)", "For ringworm"),
    drug("Econazole Cream 1%", "Topical antifungal"),
    drug("Hydrocortisone Cream 1%", "Mild topical steroid"),
    drug("Hydrocortisone Cream 2.5%", "Moderate topical steroid"),
    drug("Betamethasone Valerate Cream 0.1%", "Potent topical steroid"),
    drug("Betamethasone + Gentamicin Cream", "Steroid + antibiotic cream"),
    drug("Betamethasone + Clotrimazole (Lotriderm)", "Steroid + antifungal"),
    drug("Clobetasol Cream 0.05% (Dermovate)", "Very potent steroid"),
    drug("Mometasone Cream 0.1%", "Potent steroid"),
    drug("Diclofenac Gel 1% (Voltaren Emulgel)", "Topical NSAID"),
    drug("Deep Heat Rub", "Topical analgesic"),
    drug("Aboniki Balm", "Mentholated muscle balm"),
    drug("Robb Ointment", "Mentholated ointment"),
    drug("Mentholatum Ointment", "Cold rub"),
    drug("Calamine Lotion", "For rashes and itching"),
    drug("Benzyl Benzoate Lotion 25%", "For scabies"),
    drug("Permethrin Cream 5% (Lyclear)", "For scabies"),
    drug("Silver Sulfadiazine Cream 1% (Flamazine)", "For burns"),
    drug("Bactroban Ointment (Mupirocin 2%)", "Topical antibiotic"),
    drug("Fusidic Acid Cream 2% (Fucidin)", "Topical antibiotic"),
    drug("Benzoyl Peroxide Gel 5%", "For acne"),
    drug("Adapalene Gel 0.1% (Differin)", "For acne"),
    drug("Tretinoin Cream 0.025%", "For acne and anti-aging"),
    drug("Erythromycin Topical Gel 2%", "For acne"),
    drug("Acne-Aid Bar", "Soap for acne-prone skin"),
    drug("Coal Tar Shampoo (T/Gel)", "For psoriasis and dandruff"),
    drug("Ketoconazole Shampoo 2% (Nizoral)", "For seborrhoeic dermatitis"),
    drug("Zinc Pyrithione Shampoo", "For dandruff"),
  ],

  /* ─────────────────────── PAEDIATRICS ─────────────────────── */
  "Paediatrics": [
    drug("Paracetamol Drops (60mg/0.6ml)", "Infant pain and fever"),
    drug("Paracetamol Syrup 120mg/5ml", "Childrens paracetamol"),
    drug("Paracetamol Syrup 250mg/5ml", "Childrens paracetamol higher dose"),
    drug("Panadol Syrup", "Paracetamol brand syrup"),
    drug("Ibuprofen Suspension 100mg/5ml", "Childrens NSAID"),
    drug("Amoxicillin Suspension 125mg/5ml", "Paediatric antibiotic"),
    drug("Amoxicillin Suspension 250mg/5ml", "Paediatric antibiotic"),
    drug("Augmentin Suspension 228mg/5ml", "Paediatric amoxicillin/clavulanate"),
    drug("Augmentin Suspension 457mg/5ml", "Forte paediatric suspension"),
    drug("Cefuroxime Suspension 125mg/5ml", "Paediatric cephalosporin"),
    drug("Azithromycin Suspension 200mg/5ml", "Paediatric macrolide"),
    drug("Erythromycin Suspension 125mg/5ml", "Paediatric macrolide"),
    drug("Septrin Suspension (Cotrimoxazole)", "Paediatric TMP + SMX"),
    drug("Flagyl Suspension (Metronidazole 200mg/5ml)", "Paediatric anti-protozoal"),
    drug("Ciprofloxacin Suspension 250mg/5ml", "Paediatric fluoroquinolone"),
    drug("Lonart Suspension", "Paediatric ACT antimalarial"),
    drug("Coartem Dispersible", "ACT tablets for infants/children"),
    drug("Camosunate Paediatric", "Paediatric ACT"),
    drug("Piriton Syrup (CPM 2mg/5ml)", "Childrens antihistamine"),
    drug("Abidec Drops", "Infant multivitamin"),
    drug("Vi-Daylin Syrup", "Childrens multivitamin"),
    drug("Emvite Drops", "Infant multivitamin drops"),
    drug("Kiddivite Syrup", "Childrens multivitamin"),
    drug("Feroglobin Syrup for Kids", "Iron syrup for children"),
    drug("Zinc Sulfate Syrup", "Paediatric diarrhea management"),
    drug("Mebendazole Suspension 100mg/5ml", "Paediatric dewormer"),
    drug("Albendazole Suspension 400mg/10ml", "Paediatric dewormer"),
    drug("Gripe Water (Woodwards)", "For colic in babies"),
    drug("Bonnisan Drops (Himalaya)", "For infant digestive health"),
    drug("Dentinox Teething Gel", "For teething pain"),
    drug("Infacol (Simethicone Drops)", "For infant colic and wind"),
    drug("Nystatin Oral Drops", "For oral thrush in infants"),
  ],

  /* ─────────────────────── EYE, EAR & NASAL ─────────────────────── */
  "Eye, Ear & Nasal": [
    // Eye drops – antibiotics
    drug("Chloramphenicol Eye Drops 0.5%", "Antibiotic eye drops"),
    drug("Chloramphenicol Eye Ointment 1%", "Antibiotic eye ointment"),
    drug("Ciprofloxacin Eye Drops 0.3%", "Fluoroquinolone eye drops"),
    drug("Gentamicin Eye Drops 0.3%", "Aminoglycoside eye drops"),
    drug("Tobramycin Eye Drops 0.3%", "Aminoglycoside eye drops"),
    drug("Ofloxacin Eye Drops 0.3%", "Fluoroquinolone eye drops"),
    drug("Fusidic Acid Eye Drops (Fucithalmic)", "Topical antibiotic eye drops"),
    drug("Tetracycline Eye Ointment 1%", "Antibiotic eye ointment"),
    // Eye drops – steroids / combos
    drug("Dexamethasone Eye Drops 0.1%", "Steroid eye drops"),
    drug("Prednisolone Eye Drops 1%", "Steroid eye drops"),
    drug("Maxitrol Eye Drops (Neomycin + Polymyxin + Dexamethasone)", "Antibiotic + steroid"),
    drug("Chloramphenicol + Dexamethasone Eye Drops", "Antibiotic + steroid"),
    // Glaucoma
    drug("Timolol Eye Drops 0.25%", "Beta-blocker for glaucoma"),
    drug("Timolol Eye Drops 0.5%", "Beta-blocker for glaucoma"),
    drug("Latanoprost Eye Drops 0.005% (Xalatan)", "Prostaglandin for glaucoma"),
    drug("Bimatoprost Eye Drops (Lumigan)", "Prostaglandin for glaucoma"),
    drug("Dorzolamide + Timolol (Cosopt)", "Combination glaucoma drops"),
    // Lubricants
    drug("Artificial Tears (Tears Naturale)", "Lubricating eye drops"),
    drug("Visine Eye Drops", "Redness reliever"),
    drug("Systane Ultra Eye Drops", "Lubricating drops for dry eyes"),
    // Ear
    drug("Otosporin Ear Drops", "Antibiotic + steroid ear drops"),
    drug("Sofradex Ear Drops", "Antibiotic + steroid ear drops"),
    drug("Waxsol Ear Drops", "Ear wax remover"),
    drug("Olive Oil Ear Drops", "Natural ear wax softener"),
    drug("Ciprofloxacin Ear Drops 0.3%", "Antibiotic ear drops"),
    // Nasal
    drug("Otrivin Nasal Spray Adult (Xylometazoline 0.1%)", "Nasal decongestant"),
    drug("Otrivin Nasal Drops Paediatric (Xylometazoline 0.05%)", "Nasal decongestant for children"),
    drug("Afrin Nasal Spray (Oxymetazoline)", "Nasal decongestant"),
    drug("Normal Saline Nasal Drops", "Nasal wash"),
    drug("Flixonase Aqueous Nasal Spray (Fluticasone)", "For allergic rhinitis"),
    drug("Nasonex Nasal Spray (Mometasone)", "For allergic rhinitis"),
  ],

  /* ─────────────────────── ANTIFUNGALS ─────────────────────── */
  "Antifungals": [
    drug("Fluconazole 50mg", "Oral antifungal"),
    drug("Fluconazole 150mg", "Single dose oral antifungal"),
    drug("Fluconazole 200mg", "Oral antifungal for systemic infections"),
    drug("Itraconazole 100mg (Sporanox)", "Broad-spectrum oral antifungal"),
    drug("Ketoconazole 200mg (Nizoral)", "Oral antifungal"),
    drug("Griseofulvin 125mg", "Oral antifungal for ringworm"),
    drug("Griseofulvin 500mg", "Oral antifungal"),
    drug("Terbinafine 250mg (Lamisil)", "Oral antifungal for nails"),
    drug("Voriconazole 200mg", "Oral antifungal for systemic mycoses"),
    drug("Nystatin Oral Drops", "For oral thrush in infants"),
    drug("Nystatin 500,000 IU Tablets", "For GI candidiasis"),
    drug("Clotrimazole Cream 1%", "Topical antifungal"),
    drug("Ketoconazole Cream 2%", "Topical antifungal"),
    drug("Terbinafine Cream 1% (Lamisil)", "Topical antifungal for ringworm"),
    drug("Clotrimazole Pessaries 500mg", "Vaginal antifungal single dose"),
    drug("Clotrimazole Pessaries 200mg", "Vaginal antifungal 3-day course"),
    drug("Canesten V Cream (Clotrimazole 2%)", "Vaginal antifungal cream"),
    drug("Candid V Gel", "Vaginal antifungal gel"),
    drug("Mycoten Vaginal Tablets", "Vaginal clotrimazole"),
    drug("Ketoconazole Shampoo 2% (Nizoral)", "For scalp seborrhoeic dermatitis"),
  ],

  /* ─────────────────────── ANTIPARASITICS & DEWORMERS ─────────────────────── */
  "Antiparasitics & Dewormers": [
    drug("Albendazole 400mg (Zentel)", "Single dose broad-spectrum dewormer"),
    drug("Mebendazole 100mg (Vermox)", "Dewormer 3-day course dose"),
    drug("Mebendazole 500mg (Vermox)", "Single dose dewormer"),
    drug("Levamisole (Ketrax) 40mg", "Dewormer"),
    drug("Pyrantel Pamoate 250mg (Combantrin)", "Dewormer"),
    drug("Ivermectin 3mg", "For filariasis, scabies, lice"),
    drug("Ivermectin 6mg", "Higher dose ivermectin"),
    drug("Praziquantel 600mg", "For schistosomiasis and tapeworm"),
    drug("Tinidazole 500mg (Fasigyn)", "Anti-protozoal for giardia/amoeba"),
    drug("Secnidazole 2g", "Single dose anti-protozoal"),
    drug("Ornidazole 500mg", "Anti-protozoal"),
    drug("Diloxanide Furoate 500mg (Furamide)", "Amoebicide"),
    drug("Chloroquine Phosphate 250mg", "For amoebic hepatitis"),
    drug("Benzyl Benzoate Lotion 25%", "For scabies"),
    drug("Permethrin Cream 5% (Lyclear)", "For scabies and head lice"),
  ],

  /* ─────────────────────── HORMONES, CONTRACEPTIVES & MEN'S HEALTH ─────────────────────── */
  "Hormones, Contraceptives & Men's Health": [
    drug("Postinor-2 (Levonorgestrel 1.5mg)", "Emergency contraceptive"),
    drug("Lydia Contraceptive Pill", "Combined oral contraceptive"),
    drug("Microgynon (Levonorgestrel + EE)", "Combined oral contraceptive"),
    drug("Exluton (Linestrenol)", "Progestogen-only mini-pill"),
    drug("Marvelon (Desogestrel + EE)", "Combined oral contraceptive"),
    drug("Yasmin (Drospirenone + EE)", "Combined oral contraceptive"),
    drug("Depo-Provera Injection (Medroxyprogesterone)", "3-month contraceptive injection"),
    drug("Sayana Press", "Self-injectable contraceptive"),
    drug("Norplant Implant", "Long-acting implant contraceptive"),
    drug("Clomid 50mg (Clomifene)", "Ovulation induction"),
    drug("Duphaston 10mg (Dydrogesterone)", "Progesterone supplement"),
    drug("Primolut-N (Norethisterone) 5mg", "Menstrual disorders"),
    drug("Provera (Medroxyprogesterone) 10mg", "Progestogen"),
    drug("Estradiol Patches", "HRT for menopause"),
    drug("Premarin (Conjugated Estrogens) 0.625mg", "HRT"),
    drug("Thyroxine (Levothyroxine) 50mcg", "Thyroid hormone"),
    drug("Thyroxine 100mcg", "Thyroid hormone"),
    drug("Carbimazole 5mg", "For hyperthyroidism"),
    // Men's health
    drug("Sildenafil 25mg", "For erectile dysfunction"),
    drug("Sildenafil 50mg (Viagra)", "For erectile dysfunction"),
    drug("Sildenafil 100mg", "For erectile dysfunction"),
    drug("Vega 100 (Sildenafil)", "Nigerian sildenafil brand"),
    drug("Tadalafil 5mg (Cialis)", "Daily ED / BPH"),
    drug("Tadalafil 20mg (Cialis)", "Long-acting ED"),
    drug("Vardenafil 20mg (Levitra)", "For erectile dysfunction"),
    drug("Dapoxetine 30mg", "For premature ejaculation"),
    drug("Finasteride 1mg (Propecia)", "For male pattern baldness"),
    drug("Finasteride 5mg (Proscar)", "For BPH"),
    drug("Tamsulosin 0.4mg (Flomax)", "Alpha-blocker for BPH"),
    drug("Alfuzosin 10mg", "Alpha-blocker for BPH"),
    drug("Dutasteride 0.5mg (Avodart)", "5-alpha reductase for BPH"),
    drug("Testosterone Undecanoate 40mg", "Testosterone supplementation"),
  ],

  /* ─────────────────────── MENTAL HEALTH & NEUROLOGY ─────────────────────── */
  "Mental Health & Neurology": [
    // Antidepressants
    drug("Fluoxetine 20mg (Prozac)", "SSRI antidepressant"),
    drug("Sertraline 50mg (Zoloft)", "SSRI antidepressant"),
    drug("Sertraline 100mg", "SSRI antidepressant"),
    drug("Citalopram 20mg", "SSRI antidepressant"),
    drug("Escitalopram 10mg (Cipralex)", "SSRI antidepressant"),
    drug("Amitriptyline 25mg (Tryptizol)", "Tricyclic antidepressant"),
    drug("Nortriptyline 25mg", "Tricyclic antidepressant"),
    // Antipsychotics
    drug("Haloperidol 5mg (Serenace)", "Antipsychotic"),
    drug("Haloperidol Injection 5mg/ml", "IM antipsychotic"),
    drug("Chlorpromazine 100mg (Largactil)", "Antipsychotic"),
    drug("Risperidone 2mg", "Atypical antipsychotic"),
    drug("Olanzapine 5mg (Zyprexa)", "Atypical antipsychotic"),
    drug("Quetiapine 25mg (Seroquel)", "Atypical antipsychotic"),
    // Anxiolytics / Sedatives
    drug("Diazepam 5mg (Valium)", "Benzodiazepine anxiolytic"),
    drug("Diazepam Injection 10mg/2ml", "IV/IM benzodiazepine"),
    drug("Lorazepam 1mg (Ativan)", "Benzodiazepine"),
    drug("Nitrazepam 5mg (Mogadon)", "For insomnia"),
    drug("Midazolam Injection 5mg/ml", "Short-acting benzodiazepine"),
    drug("Phenobarbitone 30mg", "Sedative / anticonvulsant"),
    // Anticonvulsants
    drug("Phenytoin 100mg (Dilantin)", "Anticonvulsant"),
    drug("Carbamazepine 200mg (Tegretol)", "Anticonvulsant and mood stabiliser"),
    drug("Valproic Acid 200mg (Epilim)", "Anticonvulsant"),
    drug("Valproic Acid 500mg SR", "Extended release anticonvulsant"),
    drug("Lamotrigine 25mg (Lamictal)", "Anticonvulsant"),
    drug("Levetiracetam 500mg (Keppra)", "Anticonvulsant"),
    drug("Clonazepam 0.5mg", "Anticonvulsant"),
    // Parkinson's
    drug("Levodopa + Carbidopa (Sinemet)", "For Parkinson's disease"),
    // Migraine
    drug("Sumatriptan 50mg (Imigran)", "For migraine"),
    drug("Ergotamine + Caffeine (Cafergot)", "For migraine"),
    // Dementia
    drug("Donepezil 5mg (Aricept)", "For Alzheimer's disease"),
  ],

  /* ─────────────────────── ANTI-HIV / ARVs ─────────────────────── */
  "Anti-HIV (ARVs)": [
    drug("TDF + 3TC + EFV (TLE 300/300/600mg)", "First-line ARV combination"),
    drug("TDF + 3TC + DTG (TLD 300/300/50mg)", "First-line ARV combination"),
    drug("Zidovudine (AZT) 300mg", "NRTI ARV"),
    drug("Lamivudine (3TC) 150mg", "NRTI ARV"),
    drug("Tenofovir (TDF) 300mg", "NRTI ARV"),
    drug("Efavirenz (EFV) 600mg", "NNRTI ARV"),
    drug("Nevirapine (NVP) 200mg", "NNRTI ARV"),
    drug("Lopinavir + Ritonavir (Kaletra)", "Protease inhibitor"),
    drug("Dolutegravir 50mg (Tivicay)", "Integrase inhibitor ARV"),
    drug("Atazanavir + Ritonavir", "Protease inhibitor"),
    drug("Cotrimoxazole Prophylaxis 960mg", "Opportunistic infection prevention"),
    drug("Fluconazole 200mg (Cryptococcal prophylaxis)", "Antifungal for HIV patients"),
    drug("Isoniazid Preventive Therapy 300mg", "TB prevention in HIV"),
  ],

  /* ─────────────────────── URINARY TRACT ─────────────────────── */
  "Urinary Tract": [
    drug("Nitrofurantoin 100mg", "For UTIs"),
    drug("Nitrofurantoin 50mg", "For UTIs"),
    drug("Nitrofurantoin Macrocrystals (Macrobid)", "Modified-release for UTIs"),
    drug("Fosfomycin 3g Granules (Monurol)", "Single dose for uncomplicated UTIs"),
    drug("Norfloxacin 400mg", "Fluoroquinolone for UTIs"),
    drug("Trimethoprim 200mg", "For uncomplicated UTIs"),
    drug("Ofloxacin 200mg", "For UTIs"),
    drug("Cephalexin 500mg", "For UTIs"),
    drug("Tamsulosin 0.4mg", "Alpha-blocker for BPH / urine flow"),
    drug("Oxybutynin 5mg", "For overactive bladder"),
    drug("Solifenacin 5mg (Vesicare)", "For overactive bladder"),
    drug("Phenazopyridine 200mg (Pyridium)", "Urinary analgesic"),
    drug("Potassium Citrate Sachets", "For kidney stones prevention"),
  ],

  /* ─────────────────────── FIRST AID, CONSUMABLES & OTHERS ─────────────────────── */
  "First Aid, Consumables & Others": [
    // Antiseptics
    drug("Methylated Spirit 70%", "Antiseptic"),
    drug("Hydrogen Peroxide 3%", "Antiseptic"),
    drug("Hydrogen Peroxide 6%", "Antiseptic wound wash"),
    drug("Iodine Tincture 2.5%", "Antiseptic"),
    drug("Dettol Liquid (Chloroxylenol)", "Disinfectant"),
    drug("Savlon Liquid (Chlorhexidine + Cetrimide)", "Antiseptic liquid"),
    drug("Povidone-Iodine Solution 10% (Betadine)", "Antiseptic"),
    drug("Cetrimide Solution", "Antiseptic"),
    // Dressings
    drug("Cotton Wool 50g", "Absorbent cotton wool"),
    drug("Cotton Wool 500g", "Hospital size cotton wool"),
    drug("Crepe Bandage 5cm", "Elastic bandage"),
    drug("Crepe Bandage 10cm", "Elastic bandage"),
    drug("Plaster Strips (Elastoplast)", "Adhesive dressings"),
    drug("Gauze Swabs 7.5cm x 7.5cm", "Sterile gauze pads"),
    drug("Zinc Oxide Plaster", "Strapping plaster"),
    drug("Micropore Tape", "Medical adhesive tape"),
    // Devices / diagnostics
    drug("Digital Thermometer", "For fever measurement"),
    drug("Syringe 2ml + Needle", "Disposable syringe"),
    drug("Syringe 5ml + Needle", "Disposable syringe"),
    drug("Syringe 10ml + Needle", "Disposable syringe"),
    drug("Syringe 20ml + Needle", "Disposable syringe"),
    drug("IV Cannula 20G", "IV access cannula"),
    drug("IV Cannula 22G", "Paediatric IV cannula"),
    drug("Giving Set (IV drip set)", "IV administration set"),
    drug("Gloves (Latex) - Medium", "Examination gloves"),
    drug("Gloves (Latex) - Large", "Examination gloves"),
    drug("Surgical Mask 3-ply", "Face mask"),
    drug("N95 Respirator Mask", "High protection mask"),
    // RDTs / Tests
    drug("Malaria RDT Kit (HRP2)", "Rapid malaria test"),
    drug("Malaria RDT Kit (Combo)", "Pf + Pv combo rapid test"),
    drug("Pregnancy Test Kit (Urine HCG)", "Urine pregnancy test"),
    drug("Blood Glucose Test Strips (Accu-Chek)", "For glucometer"),
    drug("Hepatitis B Surface Antigen (HBsAg) Test", "Hepatitis B rapid test"),
    drug("HIV Rapid Test (Determine)", "HIV screening test"),
    // Contraceptive
    drug("Condoms (Gold Circle)", "Male condom"),
    drug("Condoms (Durex)", "Male condom"),
    drug("Female Condoms (Femidom)", "Female condom"),
    // Nasal saline / Sterile water
    drug("Sodium Chloride 0.9% 1L IV Bag", "Normal saline IV infusion"),
    drug("Dextrose 5% 1L IV Bag", "5% Dextrose IV infusion"),
    drug("Ringers Lactate 1L IV Bag", "IV fluid"),
    drug("Water for Injection 10ml", "Sterile diluent"),
  ],
};

export const getSuggestionsForCategory = (category: string): Suggestion[] => {
  return menuSuggestions[category] || [];
};
